baseurl = "https://ho-oto.github.io/"
title = "Cacao's repaying"
copyright = "© Hayate Nakano"
languageCode = 'ja'
enableGitInfo = true

[params]
subtitle = "メモとか作業ログとか"

[frontmatter]
date = ["date", ":git", "lastmod", "publishDate"]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/ho-oto/"

[[params.social]]
name = "GitHub"
url = "https://github.com/ho-oto"

[[params.social]]
name = "Twitter"
url = "https://twitter.com/h8t0"

[[menu.main]]
name = "Working logs"
url = "/tags/log"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4