baseurl = "https://ho-oto.github.io/"
title = "Cacao's repaying"
copyright = "© Hayate Nakano"
languageCode = 'ja'
enableGitInfo = true

[params]
subtitle = "メモとか作業ログとか"
mainSections = ["blog"]

[frontmatter]
date = ["date", ":git", "lastmod", "publishDate"]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/ho-oto/"

[[params.social]]
name = "GitHub"
url = "https://github.com/ho-oto"

[[menu.main]]
name = "All posts"
url = "/blog"
weight = 1

[[menu.main]]
name = "Note"
url = "/note"
weight = 2

[[menu.main]]
name = "Log"
url = "/log"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5
