baseURL = 'http://example.org/'
languageCode = 'ja'
title = "Cacao's repaying"
copyright = "© Hayate Nakano"

[params]
subtitle = "メモとか作業ログとか"

[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/ho-oto/"

[[params.social]]
name = "GitHub"
url = "https://github.com/ho-oto"

[[params.social]]
name = "Twitter"
url = "https://twitter.com/h8t0"

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4