name: manage issue

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-20.04

    env:
      TZ: "Asia/Tokyo"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Create issue
        run: |
          DATE=$(date "+%Y-%m-%d")
          BODY=$(cat << EOS
          ---
          title: "ログ"
          date: $DATE
          lastmod: $DATE
          tags: []
          author : "Hayate Nakano"
          math: false
          toc: false
          ---

          EOS
          )
          gh issue create --label "log" --title "$DATE" --body "$BODY"

  close:
    needs: create
    runs-on: ubuntu-20.04
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v5
        with:
          only-issue-labels: "log"
          days-before-issue-stale: 2
          stale-issue-label: "skip"
          days-before-issue-close: 3
          repo-token: ${{ secrets.GITHUB_TOKEN }}
