name: manage issue

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-20.04

    env:
      TZ: "Asia/Tokyo"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create issue
        run: |
          DATE=$(date "+%Y-%m-%d")
          BODY=$(cat << EOS
          ---
          title: "ログ"
          date: $DATE
          lastmod: $DATE
          tags: []
          author : "Hayate Nakano"
          math: false
          toc: false
          ---

          EOS
          )
          gh issue create --label "log" --title "$DATE" --body "$BODY"

      - name: Close issue
        run: |
          for ISSUE in $(gh issue list -l "log" -s "open" --json number --jq ".[].number")
          do
            CREATED=$(gh issue view ${ISSUE} --json createdAt --jq ".createdAt|fromdate")
            UPDATED=$(gh issue view ${ISSUE} --json updatedAt --jq ".updatedAt|fromdate")
            [ $CREATED -ne $UPDATED ] && continue
            TODAY=$(date "+%s")
            if [ $(( ($TODAY - $CREATED) / (60 * 60 * 24) )) -gt 3 ]; then
              gh issue edit ${ISSUE} --add-label "skip"
              gh issue close ${ISSUE}
            fi
          done