name: generate from notion

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-22.04
    env:
      TZ: "Asia/Tokyo"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Setup
        run: |
          pipx install poetry==1.2.1
          poetry install --no-root --no-dev

      - name: Pandoc Setup
        run: |
          curl https://github.com/jgm/pandoc/releases/download/3.0.1/pandoc-3.0.1-1-amd64.deb -Lo pandoc-3.0.1-1-amd64.deb
          sudo dpkg -i pandoc-3.0.1-1-amd64.deb
          curl https://github.com/ho-oto/notion2pandoc/releases/download/v0.5.0/notion2pandoc-x86-64-linux.tar.gz -Lo notion2pandoc-x86-64-linux.tar.gz
          tar xf notion2pandoc-x86-64-linux.tar.gz
          sudo mv notion2pandoc-x86-64-linux/notion2pandoc /usr/local/bin
          pandoc --version
          notion2pandoc --version

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: generate
        run: ./.venv/bin/python generate_from_notion.py
        env:
          NOTION_DB_UUID: ${{ secrets.NOTION_DB_UUID }}
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          NOTION_AUTHOR: ${{ secrets.NOTION_AUTHOR }}
          NOTION_ABOUT_ME_ID: ${{ secrets.NOTION_ABOUT_ME_ID }}


      - name: commit
        run: |
          git config --local user.email "22756928+ho-oto@users.noreply.github.com"
          git config --local user.name "ho-oto"
          git add -A content/*
          git commit -m "[bot] generate from notion" || exit 0
          git push origin main

      - name: Build
        run: hugo -F

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
