name: convert issue to post

on:
  issues:
    types:
      - "closed"

jobs:
  push:
    runs-on: ubuntu-20.04

    if: |
      contains(github.event.issue.labels.*.name, 'log') ||
      contains(github.event.issue.labels.*.name, 'note') ||
      contains(github.event.issue.labels.*.name, 'blog')

    env:
      TZ: "Asia/Tokyo"
      ISSUE: ${{ github.event.issue.html_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set env
        run: |
          echo "ISSUE_TITLE=$(gh issue view ${ISSUE} --json title --jq ".title")" >> $GITHUB_ENV
          [ $(gh issue view ${ISSUE} --json labels --jq 'any(.labels[].name; . == "log")') = "true" ] && OUT_DIR=log
          [ $(gh issue view ${ISSUE} --json labels --jq 'any(.labels[].name; . == "note")') = "true" ] && OUT_DIR=note
          [ $(gh issue view ${ISSUE} --json labels --jq 'any(.labels[].name; . == "blog")') = "true" ] && OUT_DIR=blog
          [ -z "${OUT_DIR}" ] && exit 1
          echo "OUT_DIR=${OUT_DIR}" >> $GITHUB_ENV

      - name: check not duplicate
        run: |
          ! test -f "content/${OUT_DIR}/${ISSUE_TITLE}.md"

      - name: check modified
        run: |
          test \
          $(gh issue view ${ISSUE} --json updatedAt --jq ".updatedAt") != \
          $(gh issue view ${ISSUE} --json createdAt --jq ".createdAt")

      - name: make file
        run: |
          gh issue view ${ISSUE} --json body --jq ".body" > "content/${OUT_DIR}/${ISSUE_TITLE}.md"

      - name: commit and push
        run: |
          git config --local user.email "22756928+ho-oto@users.noreply.github.com"
          git config --local user.name "ho-oto"
          git add "content/log/${ISSUE_TITLE}.md"
          git commit -m "$ISSUE_TITLE"
          git push origin main

      - uses: ./.github/workflows/gh-pages
