name: convert issue to post

on:
  issues:
    types:
      - "closed"

jobs:
  push:
    runs-on: ubuntu-20.04

    if: |
      contains(github.event.issue.labels.*.name, 'log') ||
      contains(github.event.issue.labels.*.name, 'note') ||
      contains(github.event.issue.labels.*.name, 'blog')

    env:
      TZ: "Asia/Tokyo"
      ISSUE: ${{ github.event.issue.html_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set env
        run: |
          echo "ISSUE_TITLE=$(gh issue view ${ISSUE} --json title --jq ".title")" >> $GITHUB_ENV
          [ $(gh issue view ${ISSUE} --json labels --jq 'any(.labels[].name; . == "log")') = "true" ] && OUT_DIR=content/log
          [ $(gh issue view ${ISSUE} --json labels --jq 'any(.labels[].name; . == "note")') = "true" ] && OUT_DIR=content/note
          [ $(gh issue view ${ISSUE} --json labels --jq 'any(.labels[].name; . == "blog")') = "true" ] && OUT_DIR=content/blog
          [ -z "${OUT_DIR}" ] && exit 1
          echo "OUT_DIR=${OUT_DIR}" >> $GITHUB_ENV

      - name: Check not duplicate
        run: |
          ! test -f "${OUT_DIR}/${ISSUE_TITLE}.md"

      - name: Check modified
        run: |
          test \
          $(gh issue view ${ISSUE} --json updatedAt --jq ".updatedAt") != \
          $(gh issue view ${ISSUE} --json createdAt --jq ".createdAt")

      - name: Commit and push
        run: |
          git config --local user.email "22756928+ho-oto@users.noreply.github.com"
          git config --local user.name "ho-oto"
          gh issue view ${ISSUE} --json body --jq ".body" > "${OUT_DIR}/${ISSUE_TITLE}.md"
          git add "${OUT_DIR}/${ISSUE_TITLE}.md"
          git commit -m "[bot] add ${ISSUE_TITLE}.md"
          git push origin main

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo

      - name: Debug
        run: ls public/log

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
