name: convert issue to post

on:
  issues:
    types:
      - "closed"

jobs:
  push:
    runs-on: ubuntu-20.04

    if: |
      ( contains(github.event.issue.labels.*.name, 'log')  ||
        contains(github.event.issue.labels.*.name, 'note') ||
        contains(github.event.issue.labels.*.name, 'blog') ) &&
      ( ! contains(github.event.issue.labels.*.name, 'skip') )

    env:
      TZ: "Asia/Tokyo"
      ISSUE: ${{ github.event.issue.html_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set env
        run: |
          ISSUE_TITLE=$(gh issue view ${ISSUE} --json title --jq ".title")
          LABELS=$(gh issue view ${ISSUE} --json labels --jq '.labels[].name')

          echo $LABELS | grep '^log$'  && OUT_DIR=content/log
          echo $LABELS | grep '^note$' && OUT_DIR=content/note
          echo $LABELS | grep '^blog$' && OUT_DIR=content/blog
          OUT_FILE="${OUT_DIR}/${ISSUE_TITLE}.md"

          echo "ISSUE_TITLE=${ISSUE_TITLE}" >> $GITHUB_ENV
          echo "OUT_FILE=${OUT_FILE}" >> $GITHUB_ENV

      - name: Commit and push
        if: startsWith(env.OUT_FILE, 'content/')
        run: |
          git config --local user.email "22756928+ho-oto@users.noreply.github.com"
          git config --local user.name "ho-oto"

          gh issue view ${ISSUE} --json body --jq ".body" > "${OUT_FILE}"
          git add "${OUT_FILE}" || exit 0
          git commit -m "[bot] add ${ISSUE_TITLE}.md"
          git push origin main

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
